export const TEXT = {
  SUBJECTIVE: `Subjective`,
  CHIEF: `Chief Complaint: `,
  HISTORY: `History of Present Illness: `,
  HISTORY_WHO: ` who presents to clinic with complaint of a painful ingrown toenail on the `,
  HISTORY_TOE: ` toe. Onset of pain, swelling, and redness started `,
  HISTORY_AGO: ` ago. Patient experiences a lot of pain with weightbearing and any pressure over the area. Patient has tried soaking the foot in warm water, which provided only limited amount of improvement in the symptoms. No other treatment has been attempted to date. Patient denies previous history of this condition. Patient denies any trauma to this area. Patient denies F/C/N/V.`,
  PHYSICAL_EXAM: `Physical Exam`,
  GENERAL_APPEARANCE: `GENERAL APPEARANCE - Patient is very pleasant, well-dressed and in good hygiene. Alert and oriented x3. In no acute distress.`,
  DERM: `DERM: Severely incurvated `,
  BORDER: ` border of the `,
  NAIL: ` nail. Ungual labia is erythematous, edematous and tender.`,
  EVIDENCE: ` Evidence of previous nail wedge resection. No serous drainage is noted. All other nails are intact without evidence of dystrophy. Interdigital spaces are clean and dry bilaterally. No open wounds or sores bilaterally. There is good skin turgor and texture bilaterally. No hyperkeratotic lesions noted bilaterally. `,
  NEURO: `NEURO: light touch sensation intact bilaterally. Proprioception intact bilaterally. Muscle testing 5/5 anterior, lateral and posterior muscle groups bilaterally.`,
  VASC: `VASC: Pedal pulses are `,
  CAPILLARY: `Capillary filling time`,
  TIME: ` 3 seconds. Hair growth is present over the foot and leg bilaterally. No edema noted over lower extremity bilaterally. No evidence of varicosities bilaterally. Temperature warm to cool from the tibial tuberosity to the toes bilaterally.`,
  MS: `M/S: Muscle testing 5/5 for the anterior, lateral and posterior muscle group bilaterally. Range of motion of the forefoot, midfoot and rear foot was good without crepitations or pain. tenderness to palpation at `,
  NAIL_BORDER: ` nail border of `,
  TOE: ` toe. `,
  ASSESSMENT_PLAN: `ASSESSMENT/PLAN:`,
  PAIN: `# Pain in `,
  PARONYCHIA: `# Paronychia of `,
  HASH: `# `,
  ONYCHOCRYPTOSIS: ` border onychocryptosis of the `,
  DISCUSSED: `- Discussed clinical findings and treatment plan.`,
  TREATMENT_OPTIONS: `- Treatment options consisting of: 1. observation, 2. soaks, and minor surgery options such as: 3. partial nail avulsion, and 4. partial matrixectomy 5. Complete nail avulsion have been discussed.`,
  PT_PROCEDURE: `- Pt would like to proceed with `,
  PT_INSTRUCTION: ` nail avulsion. Explained to the patient that chances of reoccurrence of ingrown nail are possible after procedure, and that continued/worsening pain and infection are possible if procedure is not performed. Patient understands risks benefits alternatives and post procedure course and wants to proceed.`,
  SEE_PROCEDURE_NOTE: `- See procedure note below`,
  POST_CARE: `- Pt instructed to remove dressing tomorrow and then soak daily in warm water with epsom salts for 1-2wks.`,
  HANDOUT: `- Handout for post procedure care given`,
  INFECTION_SIGNS: `- Advised on sign of infection such as but not limited to fever, chills, pus, excess, pain redness that would warrant earlier appointment or visit to Emergency room`,
  RTC: `- RTC 2 weeks`,
  PROCEDURE_NOTE: `Procedure Note: Correct side site procedure confirmed, consent obtained. A total of 5ml of 2% Lidocaine was injected into the `,
  TOE_FORM: ` toe in form of digital block. The toe was prepped in the usual aseptic manner. `,
  NAIL_AVULSION: ` nail avulsion `,
  PHENOL: ` phenol was performed using a sterile nail pack. Adaptic, bacitracin & dry sterile dressing applied with coban.`,
}
