export const TEXT = {
  SUBJECTIVE: `Subjective`,
  CHIEF: `Chief Complaint: `,
  HISTORY: `History of Present Illness: `,
  HISTORY_WHO: ` who presents to clinic with complaint of `,
  HISTORY_HEEL: ` heel pain. Pain first appeared `,
  HISTORY_AGO: ` ago. Pain has been increasing since onset. Pain is sharp and localized and present with weightbearing and particularly increased after periods of rest, consistent with post-static dyskinesia. Patient reports increase in activity prior to onset. Has tried `,
  DENIES_FALLS: `. Denies falls, injuries trauma or other pedal complications. Denies previous history of this condition. Denies change in shoegear or activities.`,
  PHYSICAL_EXAM: `Physical Exam`,
  GENERAL_APPEARANCE: `GENERAL APPEARANCE - Patient is very pleasant, well-dressed and in good hygiene. Alert and oriented x3. In no acute distress.`,
  LE_EXAM: `LE EXAM`,
  VASC: `VASC: Pedal pulses are `,
  CAPILLARY: `Capillary filling time`,
  TIME: ` 3 seconds + digital hair.`,
  DERM: `DERM: Skin is warm to touch. No cyanosis. No skin atrophy. No erythema, no edema, no ecchymosis, no open lesions noted bilaterally. `,
  NEURO: `NEURO: Sensory and motor function grossly intact bilaterally.`,
  MSK: `MSK: No pain with lateral sqeeze test of the `,
  HEEL: ` heel. `,
  TTP: `TTP of `,
  MEDIAL: ` medial `,
  LATERAL: ` lateral `,
  CALCANEAL: `calcaneal tubercle`,
  TENDERNESS: `Tenderness along length of plantar fascia`,
  NO_TENDERNESS: `No tenderness of Achilles or PT tendon`,
  LEFT: `LEFT `,
  RIGHT: `RIGHT `,
  AJ: `AJ dorsiflexion`,
  DEGREE_EXTENDED: ` degrees with knee extended, to `,
  DEGREE_FLEXED: ` degrees with knee flexed. `,
  FIVE: `5/5 muscle strength without pain of all leg/foot muscles bilaterally`,
  JAYS: `AJ, STJ, MTJ, MPJs, range of motion fluid, painless, and WNL bilatrally`,
  ASSESSMENT_PLAN: `ASSESSMENT/PLAN:`,
  GASTROC: `#  Gastroc Equinus `,
  TOE: ` toe. `,
  PES: `# Pes Planus `,
  PAIN: `# Pain `,
  FOOT: ` foot. `,
  ENTHESOPATHY: `# Enthesopathy `,
  PLANTAR_FASCIITIS: `# Plantar Fasciitis `,
  CONDITION_ETIOLOGY_TREATMENT: `- Condition, etiology and treatment options discussed with patient. Instructional handout provided.`,
  ADVISED_NSAIDS: `- Advised patient to take OTC NSAIDS as needed for pain. Risks discussed such as but not limited to kidney complications, GI ulcers, bleeding complications.`,
  ANTI_INFLAMMATORY: `- If anti-inflammatory are not sufficient in addressing symptoms then Medrol dose pack can be considered this was discussed in detail`,
  STRETCHING_EXERCISES: `- Stretching exercises emphasized, at least 4-5 times daily`,
  ICE_TO_PAINFUL_AREA: `- Ice to painful area, 10 - 15 minutes at a time`,
  ADVISED_SHOES: `- Advised patient to wear shoes with good heel and arch support such as cross-training or running shoes. Avoid wearing flat shoes, sandals, or slippers, or going barefoot.`,
  NIGHT_SPLINT: `- Night splint dispensed and educated on proper use`,
  OTC_INSERT: `- OTC insert dispensed and educated on proper use`,
  DISCUSSED_CUSTOM_INSERTS: `- Discussed custom inserts and patient may opt for them in future if no improvement with current treatment options`,
  SURGICAL_OPTIONS: `- Also discussed surgical options such as open plantar fasciotomy if no improvement seen if conservative options fail, patient understands risks, benefits, alternatives and post-operative course and is not amenable at this time`,
  STEROID_INJECTION: `- Discussed risk benefits alternatives to steroid injection today, patient understands that the injection will help with pain and inflammation but will not resolve underlying biomechanical issues and will still need to wear proper shoes, inserts and do stretching. Patient understands risks benefits alternatives and is amenable to injection today, verbal consent obtained.`,
  PROCEDURE_NOTE: `Procedure Note`,
  TIMEOUT: `Timeout performed, correct side site confirmed, consent obtained.`,
  INJECTED: `- Injected 3ml of 2:1 mixture of 0.5% Marcaine plain, Dex 4mg to `,
  BANDAID: ` heel, band-aid applied, patient noted relief in symptoms prior to leaving clinic.`,
  DISCUSSED_SIGNS: `- Discussed signs and symptoms of potential steroid flare, advised to rest and ice the area if it occurs`,
  RTC: `RTC  in `,
  CALL: `Call or email if any question or concerns.`,
}
